
version: 2
jobs:
  check-description-files:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
      - checkout
      - run:
          name: Check for expected filenames
          command: |
            unexpected_files=$(find . -mindepth 1 \( -type d \( -path ./.circle -o -path ./.git \) -o -type f \( -name README.md -o -name "*.s4ext"  \)  \)  -prune -o -print)
            for unexpected_file in $unexpected_files; do
              echo $unexpected_file
            done
            [[ $unexpected_files != "" ]] && exit 1

workflows:
  version: 2
  test:
    jobs:
      - check-description-files
