name: Extensions Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 */1 * *

jobs:
  notifier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install requests==2.31.0 pandas==2.1.1 logging==0.4.9.6 PyGithub==2.1.1 

    - name: Run Python script to calculate errors
      run: |
        python .github/generate_codeowners.py
        python .github/notify_extension_managers.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

